// GENERATED by escanor-desktop/scripts/sync-phone-lib.mjs from packages/remote/src/phone/client.ts. Do not edit here.
/**
 * The phone's side of the channel. Portable: it uses only `fetch`, `WebSocket` and WebCrypto, so the phone app (a web view)
 * and the Node tests run exactly this file.
 *
 * Route: LAN first (direct, free, nothing leaves the building); if the computer is not reachable that way, the Escanor cloud
 * relay (end-to-end encrypted, the cloud only passes sealed messages along).
 */
import type { ClientMsg, PairingPayload, ServerMsg } from './protocol';
import { phoneRedeem } from './redeem';
import { openRelayResponse, sealRelayRequest } from './relay-seal';
import { b64u, clientProof, open, parseCode, randomBytes, seal, serverProof, sessionKey, timingSafeEqual } from './secure';

export interface PairedComputer {
  /** The device id this phone was given. */
  id: string;
  name: string;
  /** 32-byte device key, base64url. Keep it in the most private storage the platform has. */
  key: string;
  /** `host:port` addresses to try on the local network, best first. */
  lan: string[];
  /** Escanor machine id, for the cloud route. */
  agentId: string | null;
  pairedAt: string;
}

export type Route = 'lan' | 'cloud';

/** Sends one sealed blob to this computer through the Escanor cloud and returns the sealed reply. The app implements it with its signed-in API client. */
export type RelayTransport = (req: { agentId: string; deviceId: string; sealed: string }) => Promise<string>;

export interface ClientEnv {
  fetch?: typeof fetch;
  WebSocket?: typeof WebSocket;
  relay?: RelayTransport | null;
  lanTimeoutMs?: number;
  now?: () => number;
}

const withTimeout = <T>(p: Promise<T>, ms: number, what: string): Promise<T> =>
  new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error(`${what} timed out`)), ms);
    p.then((v) => (clearTimeout(t), resolve(v)), (e) => (clearTimeout(t), reject(e)));
  });

/** Pair with a computer using what its QR code (or typed code) says. Tries each local address until one answers. */
export async function pairWithPayload(payload: PairingPayload, deviceName: string, env: ClientEnv = {}): Promise<PairedComputer> {
  const doFetch = env.fetch ?? fetch;
  if (payload.v !== 1) throw new Error('This pairing code is from a newer version of Escanor. Update the app.');
  const secret = parseCode(payload.code);
  let lastError: unknown = new Error('This computer could not be reached on the local network.');
  for (const addr of payload.lan) {
    try {
      const base = `http://${addr}`;
      const got = await phoneRedeem(secret, deviceName, async (body) => {
        const res = await withTimeout(doFetch(`${base}/pair`, { method: 'POST', body: JSON.stringify(body) }), env.lanTimeoutMs ?? 4000, 'Pairing');
        if (!res.ok) throw new Error(((await res.json().catch(() => ({}))) as { error?: string }).error ?? `The computer refused (${res.status}).`);
        return (await res.json()) as { deviceId: string; sealedKey: string };
      });
      return { id: got.deviceId, name: payload.machine, key: b64u.encode(got.key), lan: payload.lan, agentId: payload.agentId, pairedAt: new Date().toISOString() };
    } catch (e) {
      lastError = e;
      // A refusal ("code did not match", "no active pairing") is final; only a network failure moves on to the next address.
      if (e instanceof Error && !/timed out|fetch|network|failed|ECONN|abort/i.test(e.message)) throw e;
    }
  }
  throw lastError;
}

type Pending = { resolve: (m: ServerMsg[]) => void; reject: (e: Error) => void; match: (m: ServerMsg) => boolean; got: ServerMsg[]; done: (got: ServerMsg[]) => boolean };

/** One live link to one paired computer. */
export class ComputerClient {
  private ws: WebSocket | null = null;
  private sk: Uint8Array | null = null;
  private seqIn = 0;
  private seqOut = 0;
  private pending = new Set<Pending>();
  private push = new Set<(m: ServerMsg) => void>();
  private stateListeners = new Set<(r: Route | null) => void>();
  private _route: Route | null = null;
  private key: Uint8Array;
  private env: Required<Pick<ClientEnv, 'lanTimeoutMs'>> & ClientEnv;

  constructor(readonly computer: PairedComputer, env: ClientEnv = {}) {
    this.key = b64u.decode(computer.key);
    this.env = { lanTimeoutMs: 3000, ...env };
  }

  get route(): Route | null {
    return this._route;
  }

  onRoute(cb: (r: Route | null) => void): () => void {
    this.stateListeners.add(cb);
    return () => this.stateListeners.delete(cb);
  }

  /** Messages the computer pushes on its own: approvals, events, stats. LAN only. */
  onPush(cb: (m: ServerMsg) => void): () => void {
    this.push.add(cb);
    return () => this.push.delete(cb);
  }

  private setRoute(r: Route | null) {
    if (r !== this._route) {
      this._route = r;
      this.stateListeners.forEach((l) => l(r));
    }
  }

  /** Connect the best way available. Resolves with the route used; rejects if neither works. */
  async connect(): Promise<Route> {
    for (const addr of this.computer.lan) {
      try {
        await withTimeout(this.openLan(addr), this.env.lanTimeoutMs, 'The local connection');
        this.setRoute('lan');
        return 'lan';
      } catch {
        this.dropSocket();
      }
    }
    if (this.env.relay && this.computer.agentId) {
      this.setRoute('cloud');
      return 'cloud';
    }
    this.setRoute(null);
    throw new Error('This computer is not reachable. Check it is on, and that your phone is on the same Wi-Fi (or turn on "Away from home" on the computer).');
  }

  private dropSocket() {
    try {
      this.ws?.close();
    } catch {
      // already closed
    }
    this.ws = null;
    this.sk = null;
  }

  private async openLan(addr: string): Promise<void> {
    const WS = this.env.WebSocket ?? WebSocket;
    const ws = new WS(`ws://${addr}/session`);
    this.ws = ws;
    this.seqIn = 0;
    this.seqOut = 0;
    const raw: string[] = [];
    let wake: (() => void) | null = null;
    let closed = false;
    ws.onmessage = (ev) => (raw.push(String(ev.data)), wake?.());
    ws.onclose = () => {
      closed = true;
      wake?.();
      if (this.ws === ws) {
        this.ws = null;
        this.sk = null;
        this.pending.forEach((p) => p.reject(new Error('The connection to the computer was closed.')));
        this.pending.clear();
        this.setRoute(this.env.relay && this.computer.agentId ? 'cloud' : null);
      }
    };
    await new Promise<void>((res, rej) => ((ws.onopen = () => res()), (ws.onerror = () => rej(new Error('connection failed')))));
    const next = async (): Promise<any> => {
      while (raw.length === 0) {
        if (closed) throw new Error('closed');
        await new Promise<void>((r) => (wake = r));
        wake = null;
      }
      return JSON.parse(raw.shift()!);
    };

    const nonceC = b64u.encode(randomBytes(16));
    ws.send(JSON.stringify({ t: 'hello', deviceId: this.computer.id, nonceC }));
    const ch = await next();
    // Prove it is the real computer: only the holder of the device key can produce this proof.
    if (!timingSafeEqual(await serverProof(this.key, nonceC, ch.nonceS), b64u.decode(String(ch.proof)))) throw new Error('That is not your computer.');
    ws.send(JSON.stringify({ t: 'auth', proof: b64u.encode(await clientProof(this.key, nonceC, ch.nonceS)) }));
    const sk = await sessionKey(this.key, nonceC, ch.nonceS);
    this.sk = sk;
    const aadIn = `lan:${this.computer.id}:s2c`;

    const first = await next(); // the computer's greeting proves the session works
    const open1 = JSON.parse(new TextDecoder().decode(await open(sk, String(first.c), aadIn))) as { s: number; m: ServerMsg };
    if (open1.m.t !== 'hello') throw new Error('Unexpected reply from the computer.');
    this.seqIn = open1.s;

    // From here on, frames are read as they arrive.
    void (async () => {
      try {
        for (;;) {
          const f = await next();
          const { s, m } = JSON.parse(new TextDecoder().decode(await open(sk, String(f.c), aadIn))) as { s: number; m: ServerMsg };
          if (!(s > this.seqIn)) continue;
          this.seqIn = s;
          this.deliver(m);
        }
      } catch {
        // closed or unauthenticated: the onclose handler cleans up
      }
    })();
  }

  private deliver(m: ServerMsg): void {
    for (const p of this.pending) {
      if (p.match(m)) {
        p.got.push(m);
        if (p.done(p.got)) {
          this.pending.delete(p);
          p.resolve(p.got);
        }
        return;
      }
    }
    this.push.forEach((l) => l(m));
  }

  /** Send a request and collect its replies, over whichever route is live. */
  async request(msg: ClientMsg, opts: { timeoutMs?: number } = {}): Promise<ServerMsg[]> {
    if (!this._route) await this.connect();
    if (this._route === 'lan' && this.ws && this.sk) {
      try {
        return await this.requestLan(msg, opts.timeoutMs ?? 60_000);
      } catch (e) {
        if (!(this.env.relay && this.computer.agentId)) throw e;
        this.dropSocket(); // the local link failed mid-request: use the cloud for this one
        this.setRoute('cloud');
      }
    }
    return this.requestCloud(msg);
  }

  private requestLan(msg: ClientMsg, timeoutMs: number): Promise<ServerMsg[]> {
    const id = 'id' in msg ? (msg as { id: string }).id : null;
    const type = msg.t;
    return new Promise<ServerMsg[]>((resolve, reject) => {
      const p: Pending = {
        resolve,
        reject,
        got: [],
        // replies carry the request id (call, chat); the rest are matched by their type
        match: (m) => (id ? ((m.t === 'result' || m.t === 'reply' || m.t === 'error') && (m as { id?: string }).id === id) : (type === 'list' && m.t === 'capabilities') || (type === 'pending' && m.t === 'pending') || (type === 'ping' && m.t === 'pong')),
        done: () => true,
      };
      const t = setTimeout(() => (this.pending.delete(p), reject(new Error('The computer did not answer in time.'))), timeoutMs);
      const finish = p.resolve;
      p.resolve = (m) => (clearTimeout(t), finish(m));
      const fail = p.reject;
      p.reject = (e) => (clearTimeout(t), fail(e));
      if (type === 'approve' || type === 'subscribe') {
        // no reply expected
        void this.sendLan(msg).then(() => p.resolve([]), p.reject);
        return;
      }
      this.pending.add(p);
      void this.sendLan(msg).catch((e) => (this.pending.delete(p), p.reject(e)));
    });
  }

  private async sendLan(msg: ClientMsg): Promise<void> {
    if (!this.ws || !this.sk) throw new Error('Not connected.');
    this.ws.send(JSON.stringify({ c: await seal(this.sk, JSON.stringify({ s: ++this.seqOut, m: msg }), `lan:${this.computer.id}:c2s`) }));
  }

  private async requestCloud(msg: ClientMsg): Promise<ServerMsg[]> {
    const relay = this.env.relay;
    if (!relay || !this.computer.agentId) throw new Error('This computer is not reachable from here.');
    const now = this.env.now?.() ?? Date.now();
    const { id, sealed } = await sealRelayRequest(this.computer.id, this.key, msg, now);
    const reply = await relay({ agentId: this.computer.agentId, deviceId: this.computer.id, sealed });
    return openRelayResponse(this.computer.id, this.key, reply, id, this.env.now?.() ?? Date.now());
  }

  /** Ask for live events and stats. Only the local route can push, so over the cloud this is a no-op. */
  async subscribe(channels: Array<'events' | 'stats'>): Promise<void> {
    if (this._route === 'lan') await this.request({ t: 'subscribe', channels });
  }

  close(): void {
    this.dropSocket();
    this.pending.forEach((p) => p.reject(new Error('Closed.')));
    this.pending.clear();
    this.setRoute(null);
  }
}

