// GENERATED by escanor-desktop/scripts/sync-phone-lib.mjs from packages/remote/src/protocol.ts. Do not edit here.
/** The shapes the phone needs from the computer's capability registry (declared here so the phone has no dependency on it). */
export interface CapabilityInfo {
  id: string;
  group: string;
  describe: string;
  risk: 'read' | 'write' | 'destructive';
  inputSchema: Record<string, unknown>;
}
export interface CapabilityEvent {
  capabilityId: string;
  callId: string;
  type: string;
  data: unknown;
}

/** Messages from the phone. Everything is sealed (AES-GCM) before it leaves the phone and opened here. */
export type ClientMsg =
  | { t: 'list' }
  | { t: 'pending' }
  | { t: 'call'; id: string; capability: string; input?: unknown }
  | { t: 'chat'; id: string; text: string }
  | { t: 'approve'; approvalId: string; ok: boolean }
  | { t: 'subscribe'; channels: Array<'events' | 'stats'> }
  | { t: 'ping' };

/** Messages to the phone. */
export type ServerMsg =
  | { t: 'hello'; machine: MachineInfo }
  | { t: 'capabilities'; items: CapabilityInfo[] }
  | { t: 'result'; id: string; ok: boolean; result?: unknown; error?: { code: string; message: string } }
  | { t: 'reply'; id: string; reply: string; listenAgain: boolean }
  | { t: 'event'; event: CapabilityEvent }
  | { t: 'approval'; approvalId: string; capabilityId: string; describe: string; risk: string; input: unknown }
  | { t: 'approval_done'; approvalId: string }
  | { t: 'pending'; approvals: Array<{ approvalId: string; capabilityId: string; describe: string; risk: string; input: unknown }> }
  | { t: 'stats'; stats: unknown }
  | { t: 'pong' }
  | { t: 'error'; id?: string; message: string };

export interface MachineInfo {
  name: string;
  hostname: string;
  os: string;
  appVersion: string;
}

/** The pairing payload shown as a QR code (and as plain text next to it). */
export interface PairingPayload {
  v: 1;
  /** The one-time pairing secret: ABCD-EFGH-… */
  code: string;
  machine: string;
  /** LAN addresses to try, `host:port`. */
  lan: string[];
  /** Backend machine id, when signed in and cloud access is on: lets the phone reach this computer away from home. */
  agentId: string | null;
}

export const PROTOCOL_VERSION = 1;
export const MAX_MESSAGE_BYTES = 256 * 1024;
export const MAX_SKEW_MS = 5 * 60_000;

/** The relay command the phone queues in the Escanor backend: plugin `desktop`, action `sealed`. */
export const RELAY_PLUGIN = 'desktop';
export const RELAY_ACTION = 'sealed';

export function isClientMsg(v: unknown): v is ClientMsg {
  if (!v || typeof v !== 'object') return false;
  const m = v as Record<string, unknown>;
  switch (m.t) {
    case 'list':
    case 'pending':
    case 'ping':
      return true;
    case 'call':
      return typeof m.id === 'string' && typeof m.capability === 'string' && m.capability.length < 100;
    case 'chat':
      return typeof m.id === 'string' && typeof m.text === 'string' && m.text.length > 0 && m.text.length <= 4000;
    case 'approve':
      return typeof m.approvalId === 'string' && typeof m.ok === 'boolean';
    case 'subscribe':
      return Array.isArray(m.channels) && m.channels.every((c) => c === 'events' || c === 'stats');
    default:
      return false;
  }
}
