// GENERATED by escanor-desktop/scripts/sync-phone-lib.mjs from packages/remote/src/phone/redeem.ts. Do not edit here.
import { b64u, open, pairProof, pairingKey } from './secure';

/** The phone's half: prove knowledge of the code, and unseal the device key it is given. */
export async function phoneRedeem(
  code: Uint8Array,
  deviceName: string,
  post: (body: { v: 1; nonce: string; proof: string; device: { name: string } }) => Promise<{ deviceId: string; sealedKey: string }>,
): Promise<{ deviceId: string; key: Uint8Array }> {
  const nonce = b64u.encode(crypto.getRandomValues(new Uint8Array(16)));
  const proof = b64u.encode(await pairProof(code, nonce, deviceName));
  const r = await post({ v: 1, nonce, proof, device: { name: deviceName } });
  return { deviceId: r.deviceId, key: await open(await pairingKey(code), r.sealedKey, `pair:${r.deviceId}`) };
}
