// GENERATED by escanor-desktop/scripts/sync-phone-lib.mjs from packages/remote/src/relay-seal.ts. Do not edit here.
import { MAX_SKEW_MS, type ClientMsg, type ServerMsg } from './protocol';
import { b64u, openJson, randomBytes, relayKey, sealJson } from './secure';

/**
 * Sealing for the cloud relay: the phone queues a command in the Escanor backend whose only content is a sealed blob, and the
 * computer answers with another. The backend stores and forwards ciphertext; it cannot read, alter or forge a message.
 * Portable (WebCrypto only): the phone app uses these same functions.
 */

export interface RelayRequest {
  id: string;
  ts: number;
  m: ClientMsg;
}
export interface RelayResponse {
  id: string;
  ts: number;
  replies: ServerMsg[];
}

const aad = (deviceId: string, dir: 'req' | 'res') => `relay:${deviceId}:${dir}`;

export async function sealRelayRequest(deviceId: string, deviceKey: Uint8Array, m: ClientMsg, now = Date.now()): Promise<{ id: string; sealed: string }> {
  const id = b64u.encode(randomBytes(12));
  return { id, sealed: await sealJson(await relayKey(deviceKey), { id, ts: now, m } satisfies RelayRequest, aad(deviceId, 'req')) };
}

export async function openRelayRequest(deviceId: string, deviceKey: Uint8Array, sealed: string): Promise<RelayRequest> {
  return openJson<RelayRequest>(await relayKey(deviceKey), sealed, aad(deviceId, 'req'));
}

export async function sealRelayResponse(deviceId: string, deviceKey: Uint8Array, res: RelayResponse): Promise<string> {
  return sealJson(await relayKey(deviceKey), res, aad(deviceId, 'res'));
}

export async function openRelayResponse(deviceId: string, deviceKey: Uint8Array, sealed: string, expectId: string, now = Date.now()): Promise<ServerMsg[]> {
  const r = await openJson<RelayResponse>(await relayKey(deviceKey), sealed, aad(deviceId, 'res'));
  if (r.id !== expectId) throw new Error('That reply belongs to a different request.');
  if (Math.abs(now - r.ts) > MAX_SKEW_MS) throw new Error('That reply is too old.');
  return r.replies;
}
