// GENERATED by escanor-desktop/scripts/sync-phone-lib.mjs from packages/remote/src/secure.ts. Do not edit here.
/**
 * Portable crypto for the phone <-> computer channel. Uses only WebCrypto (`globalThis.crypto.subtle`), which Node 22 and
 * every browser/webview provide, so the phone app runs this exact file.
 *
 *   pairing secret S ──HKDF──▶ pairing key ──seals──▶ device key K   (S travels only in the QR code)
 *   K ──HMAC──▶ mutual proofs ──HKDF──▶ session key ──AES-GCM──▶ every message (LAN)
 *   K ──HKDF──▶ relay key ──AES-GCM──▶ sealed commands through the Escanor cloud (it sees ciphertext only)
 */

const enc = new TextEncoder();
const dec = new TextDecoder();
const subtle = () => globalThis.crypto.subtle;

export const b64u = {
  encode(bytes: Uint8Array): string {
    let s = '';
    for (const b of bytes) s += String.fromCharCode(b);
    return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  },
  decode(text: string): Uint8Array {
    const pad = '='.repeat((4 - (text.length % 4)) % 4);
    const bin = atob(text.replace(/-/g, '+').replace(/_/g, '/') + pad);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  },
};

export const randomBytes = (n: number): Uint8Array => globalThis.crypto.getRandomValues(new Uint8Array(n));

/** Constant-time equality for equal-length byte strings. */
export function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

export async function hmac(key: Uint8Array, ...parts: Array<string | Uint8Array>): Promise<Uint8Array> {
  const k = await subtle().importKey('raw', key as BufferSource, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  const data = parts.map((p) => (typeof p === 'string' ? enc.encode(p) : p));
  const total = new Uint8Array(data.reduce((n, d) => n + d.length + 1, 0));
  let o = 0;
  for (const d of data) {
    total.set(d, o);
    o += d.length;
    total[o++] = 0; // separator, so ("ab","c") and ("a","bc") never collide
  }
  return new Uint8Array(await subtle().sign('HMAC', k, total));
}

/** HKDF-SHA256 to 32 bytes. */
export async function hkdf(secret: Uint8Array, salt: Uint8Array | string, info: string): Promise<Uint8Array> {
  const base = await subtle().importKey('raw', secret as BufferSource, 'HKDF', false, ['deriveBits']);
  const bits = await subtle().deriveBits({ name: 'HKDF', hash: 'SHA-256', salt: (typeof salt === 'string' ? enc.encode(salt) : salt) as BufferSource, info: enc.encode(info) }, base, 256);
  return new Uint8Array(bits);
}

async function aesKey(key: Uint8Array, usage: 'encrypt' | 'decrypt'): Promise<CryptoKey> {
  return subtle().importKey('raw', key as BufferSource, 'AES-GCM', false, [usage]);
}

/** AES-256-GCM with a fresh random IV. Output: IV (12) || ciphertext+tag, base64url. `aad` binds the message to its context. */
export async function seal(key: Uint8Array, plaintext: Uint8Array | string, aad = ''): Promise<string> {
  const iv = randomBytes(12);
  const data = typeof plaintext === 'string' ? enc.encode(plaintext) : plaintext;
  const ct = new Uint8Array(await subtle().encrypt({ name: 'AES-GCM', iv: iv as BufferSource, additionalData: enc.encode(aad) as BufferSource }, await aesKey(key, 'encrypt'), data as BufferSource));
  const out = new Uint8Array(12 + ct.length);
  out.set(iv, 0);
  out.set(ct, 12);
  return b64u.encode(out);
}

export async function open(key: Uint8Array, sealed: string, aad = ''): Promise<Uint8Array> {
  const raw = b64u.decode(sealed);
  if (raw.length < 12 + 16) throw new Error('message too short');
  try {
    return new Uint8Array(await subtle().decrypt({ name: 'AES-GCM', iv: raw.slice(0, 12) as BufferSource, additionalData: enc.encode(aad) as BufferSource }, await aesKey(key, 'decrypt'), raw.slice(12) as BufferSource));
  } catch {
    throw new Error('message could not be authenticated');
  }
}

export const sealJson = (key: Uint8Array, value: unknown, aad = '') => seal(key, JSON.stringify(value), aad);
export const openJson = async <T = unknown>(key: Uint8Array, sealed: string, aad = ''): Promise<T> => JSON.parse(dec.decode(await open(key, sealed, aad))) as T;

// ---- Pairing ---------------------------------------------------------------------------------------------------------

/** A pairing secret as shown to the person: 20 random bytes in base32, grouped (`ABCD-EFGH-…`). 160 bits: not guessable. */
const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export function newPairingSecret(): { bytes: Uint8Array; code: string } {
  const bytes = randomBytes(20);
  return { bytes, code: formatCode(bytes) };
}
export function formatCode(bytes: Uint8Array): string {
  let bits = 0;
  let value = 0;
  let out = '';
  for (const b of bytes) {
    value = (value << 8) | b;
    bits += 8;
    while (bits >= 5) {
      out += ALPHABET[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  return out.match(/.{1,4}/g)!.join('-');
}
/** Parse a typed or scanned code back to bytes. Tolerates case, spaces and dashes; rejects anything else. */
export function parseCode(code: string): Uint8Array {
  const clean = code.toUpperCase().replace(/[\s-]/g, '');
  if (!/^[A-Z2-7]{32}$/.test(clean)) throw new Error('That pairing code is not valid.');
  const out: number[] = [];
  let bits = 0;
  let value = 0;
  for (const ch of clean) {
    value = (value << 5) | ALPHABET.indexOf(ch);
    bits += 5;
    if (bits >= 8) {
      out.push((value >>> (bits - 8)) & 255);
      bits -= 8;
    }
  }
  return new Uint8Array(out);
}

export const pairingKey = (secret: Uint8Array) => hkdf(secret, 'escanor-pair-v1', 'pairing key');
export const pairProof = (secret: Uint8Array, nonce: string, deviceName: string) => hmac(secret, 'pair', nonce, deviceName);
export const relayKey = (deviceKey: Uint8Array) => hkdf(deviceKey, 'escanor-relay-v1', 'relay key');

// ---- LAN session handshake -------------------------------------------------------------------------------------------

export const serverProof = (k: Uint8Array, nonceC: string, nonceS: string) => hmac(k, 'srv', nonceC, nonceS);
export const clientProof = (k: Uint8Array, nonceC: string, nonceS: string) => hmac(k, 'cli', nonceS, nonceC);
export const sessionKey = (k: Uint8Array, nonceC: string, nonceS: string) => hkdf(k, enc.encode(`${nonceC}.${nonceS}`), 'session key');
